apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    github.com/project-slug: Makinates/${{ values.name }}
  description: ${{ values.name }} running on AWS EC2 instance managed by Terraform
spec:
  type: service
  owner: user:mrdankuta
  lifecycle: experimental