site_name: Backstage Template
# site_description: ${{values.description}}

nav:
  - Introduction: index.md
  - Template Usage: 03-Using-a-Backstage-Template.md

plugins:
  - techdocs-core

theme:
  name: material
  font: false
