apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: ec2-instance
  title: Provision an AWS EC2 Instance
  description: Provision AWS EC2 Instance using Terraform
spec:
  owner: user:mrdankuta
  type: service

  parameters:
    - title: Action
      required:
        - action
      properties:
        action:
          title: Action
          type: string
          description: Action to perform (apply/destroy)
          enum:
            - apply
            - destroy
    - title: Project Details
      required:
        - name
        - description
      properties:
        name:
          title: Project Name
          type: string
          description: Unique name. No spaces. No symbols.
          maxLength: 50
          ui:autofocus: true
          pattern: "^[a-zA-Z0-9_-]+$"
        description:
          title: Project Description
          type: string
          description: A short description
      ui:options:
        compute: parameters.action === 'apply'
    - title: EC2 Configuration
      required:
        - instanceName
        - instanceType
        - region
      properties:
        instanceName:
          title: Instance Name
          type: string
          description: The name of your EC2 instance
          ui:autofocus: true
        instanceType:
          title: EC2 Instance Type
          type: string
          enum:
            - "t2-micro"
            - "t2-small"
        region:
          title: AWS Region
          type: string
          description: The AWS region where the instance will be deployed
          enum:
            - us-east-1
            - us-west-2
      ui:options:
        compute: parameters.action === 'apply'
    - title: Existing Repository
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository URL
          type: string
          description: The URL of the repository containing the Terraform definition
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
      ui:options:
        compute: parameters.action === 'destroy'

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
      if: ${{ parameters.action === 'apply' }}
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        repoVisibility: public
        defaultBranch: "main"
        description: This is ${{ parameters.name }}
        repoUrl: "github.com?repo=${{ parameters.name }}&owner=Makinates"
      if: ${{ parameters.action === 'apply' }}
    - id: github-action
      name: Trigger GitHub Action
      action: github:actions:dispatch
      input:
        workflowId: manage-ec2.yaml
        repoUrl: ${{ 'https://github.com/Makinates/' + parameters.name if parameters.action === 'apply' else parameters.repoUrl }}
        branchOrTagName: "main"
        workflowInputs:
          instanceName: ${{ parameters.instanceName }}
          instanceType: ${{ parameters.instanceType }}
          awsRegion: ${{ parameters.region }}
          action: ${{ parameters.action }}
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: "${{ steps.publish.output.repoContentsUrl }}"
        catalogInfoPath: "/catalog-info.yaml"
      if: ${{ parameters.action === 'apply' }}

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
        if: ${{ parameters.action === 'apply' }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
        if: ${{ parameters.action === 'apply' }}
