apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    github.com/project-slug: Makinates/tf-aws-eks
    # github.com/project-slug: Makinates/${{ values.name }}
  description: ${{ values.name }} running on AWS EKS cluster managed by Terraform
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
